<a href="https://colab.research.google.com/github/imdoamaral/formacao-pnl/blob/main/redes_neurais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout
from google.colab import files

In [ ]:
files.upload()

In [4]:
spam = pd.read_csv("spam.csv")
spam.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [5]:
# fit = cria o modelo
# transform = converte texto para número

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(spam['Category'])
print(y)

[0 0 1 ... 0 0 0]


In [11]:
mensagens = spam['Message'].values
X_train, X_test, y_train, y_test = train_test_split(mensagens, y, test_size=0.3)
print(X_train)

["Go chase after her and run her over while she's crossing the street"
 'I luv u soo much u don\x92t understand how special u r 2 me ring u 2morrow luv u xxx'
 'Huh so early.. Then ü having dinner outside izzit?' ...
 'First has she gained more than  &lt;#&gt; kg since she took in. Second has she done the blood sugar tests. If she has and its ok and her blood pressure is within normal limits then no worries'
 'Ok then i come n pick u at engin?' 'Check with nuerologist.']


In [12]:
# fit apenas no teste, transform em ambos

vetorizador = CountVectorizer()
vetorizador.fit(X_train)
X_train = vetorizador.transform(X_train)

X_test = vetorizador.transform(X_test)

print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
import numpy as np
np.set_printoptions(threshold=np.inf)

X_train.toarray()[0]

In [15]:
print(X_test.shape[1])

7131


O código abaixo define a arquitetura de uma rede neural artificial sequencial para classificação. Aqui está o que cada linha faz:

1. `modelo = Sequential()`: Cria um modelo onde as camadas são empilhadas em ordem.

2. Primeira Camada (Dense):
- `units=10`: Tem 10 neurônios.
- `activation='relu'`: Usa a função ReLU para aprender padrões complexos.
- `input_dim=X_train.shape[1]`: Define a entrada com base no número de palavras (colunas) geradas pelo CountVectorizer.

3. `Dropout(0.1)`: Uma técnica de regularização que desliga 10% dos neurônios aleatoriamente durante o treino para evitar que o modelo 'decore' os dados (overfitting).

4. Camada Intermediária: Adiciona outra camada com 8 neurônios para extrair mais características.

5. Camada de Saída `(Dense(units=1))`:
- Tem apenas 1 neurônio porque é um problema de classificação binária (ou é spam, ou não é).
- `activation='sigmoid'`: Transforma a saída em uma probabilidade entre 0 e 1.

In [17]:
modelo = Sequential()
modelo.add(Dense(units=10, activation="relu", input_dim=X_train.shape[1]))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=8, activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1, activation="sigmoid"))

In [19]:
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
modelo.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 10)             │        71,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71,417 (278.97 KB)

 Trainable params: 71,417 (278.97 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
modelo.fit(X_train, y_train, epochs=20, batch_size=10, validation_data=(X_test, y_test))

Epoch 1/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9249 - loss: 0.0860 - val_accuracy: 0.9773 - val_loss: 0.0234
Epoch 2/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9869 - loss: 0.0149 - val_accuracy: 0.9839 - val_loss: 0.0148
Epoch 3/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9938 - loss: 0.0066 - val_accuracy: 0.9839 - val_loss: 0.0139
Epoch 4/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9972 - loss: 0.0035 - val_accuracy: 0.9856 - val_loss: 0.0131
Epoch 5/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9979 - loss: 0.0027 - val_accuracy: 0.9839 - val_loss: 0.0137
Epoch 6/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9982 - loss: 0.0021 - val_accuracy: 0.9833 - val_loss: 0.0140
Epoch 7/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9982 - loss: 0.0018 - val_accuracy: 0.9844 - val_loss: 0.0138
Epoch 8/20
390/390 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9987 - loss: 0.0014 - val_accuracy: 0.

In [22]:
loss, accuracy = modelo.evaluate(X_test, y_test)
print("Loss:", loss)
print("Acurácia:", accuracy)

53/53 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9856 - loss: 0.0138
Loss: 0.013789728283882141
Acurácia: 0.9856459498405457


In [ ]:
nova_previsao = modelo.predict(X_test)
print(nova_previsao)

In [ ]:
prev2 = (nova_previsao > 0.5)
print(prev2)

In [25]:
cm = confusion_matrix(y_test, prev2)
print(cm)

[[1426    2]
 [  22  222]]
